const dogJokes: string[] = [
  "Why did the dog sit in the shade? Because he didn't want to be a hot dog!",
  'What do you call a dog magician? A labracadabrador!',
  'Why was the dog a great musician? Because he had perfect pitch!',
  'What do you call a dog with a surround sound system? A sub-woofer!',
  'How does a dog stop a video? He presses the paws button!',
  'What did the dog say to the tree? Bark!',
  'What kind of dog does Dracula have? A bloodhound!',
  'What do you call a dog that can tell time? A watch dog!',
  "Why do dogs run in circles before lying down? They're trying to make a 'ruff' impression!",
  'What did the dog say when he sat on sandpaper? Ruff!',
  'What kind of dog does a scientist have? A lab!',
  "What's a dog's favorite city? New Yorkie!",
  'Why did the dog go to space? To see the bark side of the moon!',
  'What do you call a dog with a flower? A collie-flower!',
  'Why did the dog chase his tail? To catch up on his gossip!',
  'Why did the dog cross the road? To prove to the chicken it could be done!',
  'Why did the dog wear a bow tie? He was feeling formal-terrier!',
  "What did the dog say to the mailman? Thanks fur deliverin'!",
  'Why did the dog bury his bone in the sandbox? He wanted to play fetch later!',
  'Why did the police arrest the dog? He was barking without a warrant!',
  'What did the puppy say to his mom after learning to fetch? Thanks fur the support!',
  'Why did the dog bury his head in the dirt? He was looking for a worm welcome!',
  "What's the best thing about living with a Labrador? He's always retrievered to please!",
  "Why did the dachshund wear a raincoat? He didn't want to be a long short of water!",
  'Why did the dog win the spelling bee? He was pawsitively ace at alliteration!',
  "What do you call a dog with no ears? No need to listen, he doesn't care!",
  'Why did the dog go to the library? To bone up on his reading!',
  "What's the best thing about a Golden Retriever? Everything! You can't go wrong with gold.",
  'Why did the poodle get kicked out of the band? He ruff-led too many feathers!',
  'Why did the dog chase the butterfly? He wanted to see if it tasted as good as it smelled!',
  'What did the dog say when he stepped on a bee? "Ow, that\'s ruff!"',
  'Why did the dog cross the playground? To get to the other slide!',
  "What's a dog's favorite day of the week? Fetch Friday!",
  'Why did the dog wear sunglasses? He was feeling pupsthetic!',
  "Why did the dog cross the road twice? To prove he wasn't chicken… again!",
  'What did the dog say when he stepped on a cactus? "Ouch, that\'s gonna be a ruff day!"',
  'Why did the dog wear sunglasses? To look cool and canine!',
  'What\'s the best thing about a beagle? Their endless supply of "woo-woos"!',
  'Why did the dog bury his bone in the garden? He wanted to grow a bone tree!',
  'Why did the dog join the choir? He wanted to howl-l at the top of his lungs!',
  'What did the dog say after finishing his bone? "That was a-bone-solutely delicious!"',
  'Why did the dog chase his tail in circles? He was trying to catch his bark!',
  "What's the best thing about a pug? Their squished-in faces and even bigger hearts!",
  'Why did the dog wear a hat? He was having a bad hair day… fur real!',
  'Why did the dog go to the beach? To chase away the tide and claim the ocean floor as his own!',
  'What did the dog say after winning a hot dog eating contest? "I ruff-ly underestimated my appetite!"',
  'Why did the dog wear a hat? He wanted to avoid a bad hair day… again.',
  "What's the best thing about a husky? Their endless energy to pull you on sledding adventures!",
  'Why did the dog bury his bone in a cloud? He wanted it to rain treats!',
  "Why did the pirate dog wear an eyepatch? He couldn't sea clearly from that side!",
  'What did the dog say when he saw his reflection? "Now that\'s a handsome mutt!"',
  'Why did the dog go to the bakery? He wanted a pupcake!',
  "What's the best thing about a Great Dane? Their giant hugs!",
  'Why did the dog bury his bone in the sandcastle? He wanted to build a bone castle!',
];

export { dogJokes };
