const catJokes: string[] = [
  'Why was the cat sitting on the computer? Because it wanted to keep an eye on the mouse!',
  'What do you call a pile of cats? A meowtain!',
  'How do cats end a fight? They hiss and make up!',
  "What's a cat's favorite subject in school? Mewsic!",
  'What do you call a cat who can dance? A feline groovy!',
  'Why did the cat go to school? To improve its purr-spective!',
  'What do you call a cat who can swim? A catfish!',
  "What did the cat say when it was confused? I'm purr-plexed!",
  'Why are cats so good at video games? Because they have nine lives!',
  'What do you call a cat magician? A purr-former!',
  "What's a cat's favorite movie? The Sound of Mewsic!",
  'What do you call a cat with eight legs? An octo-purr!',
  'Why did the cat bring a ladder to the bar? It heard the drinks were on the house!',
  "What's a cat's favorite button on the TV remote? Paws!",
  "What did the cat say after a long day at work? I'm ex-purr-sted!",
  'Why was the cat at the beach? Because it wanted to catch some rays!',
  'What do you call a cat that likes to bowl? An alley cat!',
  'Why did the cat wear a hat? Because it wanted to stay paw-sitively stylish!',
  'What do you call a cat with a goldfish friend? An aqua-meow!',
  "What did the cat say when it broke a vase? I didn't do it. It was already in pieces when I found it!",
  'What do you call a cat that can play musical instruments? A furr-musician!',
  "What's a cat's favorite type of car? A purr-ari!",
  'What do you call a cat who can fix your car? A purr-mechanic!',
  "What's a cat's favorite type of music? Clawssical!",
  'What did the cat say when it saw a dog chasing its tail? I guess some creatures never learn how to relax!',
  'Why did the cat become a librarian? Because it wanted to keep everything in purr-fect order!',
  'What do you call a cat that can breakdance? A fur-breaker!',
  "What did the cat say when it was complimented? You've got to be kitten me!",
  "What's a cat's favorite subject in school? Scratch-ematics!",
  'Why did the cat sit on the computer? Because it wanted to keep an eye on the mouse!',
  "What's a cat's favorite game? Hide and squeak!",
  'How does a cat end a fight? It hisses and makes up!',
  'Why did the cat look at the calendar? It wanted to check how many days until Caturday!',
  'What do you call a cat that can read? Well-read!',
  'What do you call a pile of kittens? A meowtain!',
  'How does a cat end a letter? With a purr-sonal touch!',
  "What's a cat's favorite day of the week? Caturday-night!",
  'Why did the cat get detention? For purr-plagiarism!',
  'What do you call a cat who hates baths? Hissterical!',
  "How do you make a cat laugh? Tell him a hairball joke. But only once, because he won't remember it.",
  'Why did the cat cross the road? To pounce on the other side of the chicken joke!',
  'How do you know a cat has been using the computer? There are paw-sitive markings on the keys.',
  'What did the cat say when the dog won the spelling bee? I object! That word is unmeowful!',
  'Why did the cat graduate early? He had nine lives to spare!',
  "What's a cat's favorite board game? Scratchables!",
  'Why did the cat get kicked out of the library? He kept chasing the yarn ball across the aisles!',
  'Why did the cat get fired from the bakery? He kept kneading the dough with his paws.',
  'What do you call a cat who loves rainy days? A puddle jumper.',
  'How do you make a cat a millionaire? Sell him yarn for $1,000 a purr-yard.',
  'What did the cat say after he tripped over the vacuum cleaner? Dust be kitten me!',
  'Why did the cat get banned from the chess club? He kept making illegal knight moves.',
  'Why did the cat get kicked out of the bakery? He kept kneading the dough with his paws.',
  "What do you call a cat who won't answer to his name? Self-employed.",
  'Why did the cat cross the road? To prove to the dog he could.',
  'I told my cat he was overweight, and he gave me the most withering paw-ndering look.',
  "My cat's a bookworm - he purr-fers mysteries.",
  "What's a cat's least favorite subject in school? Clawculus. They always purr-form poorly.",
  'Why did the cat get detention? For hiss-terical laughter during a purr-formance of Meowbeth.',
  "What's a cat's favorite instrument? The hairballophone. It makes the most a-meow-zing sounds.",
  "What's the difference between a pun and a cat walking on a keyboard? A pun is intentional.",
  'Why did the cat win the staring contest? Nobody else had nine lives to spare.',
  'What do you call a cat that steals your underwear? A panty-raid-er.',
  "What did the cat say to the fishbowl? You're lookin' fishy.",
  'Why did the cat cross the road in a zebra costume? To confuse the chickens.',
  "What's a cat's favorite movie? The Paw-trix.",
  'What did the cat say when he fell into the river? "Meow-ayday!".',
  'My cat is on a strict diet. He only eats gourmet tuna, caviar, and the occasional sunbeam.',
  'What do you call a cat who loves to go camping? A purr-petual adventurer.',
  "What do you call a cat who's lost his voice? Speechless, of course.",
];

export { catJokes };
