const lionJokes: string[] = [
  "Why did the lion break up with his lioness girlfriend? He wanted some 'meat' time alone!",
  'What do you call a lion with a fancy hat? A dandy-lion!',
  'Why did the lion go to the doctor? He was having a pride problem!',
  "How do lions greet each other? 'Pleased to eat you!'",
  "What's a lion's favorite game? Swallow the leader!",
  'Why did the lion bring a ladder to the bar? Because he wanted to reach the mane-tenance!',
  "Why did the lioness make a great detective? She had a keen sense of 'purr-spective'!",
  'What do you call a lion who plays basketball? A jump shot!',
  'How do lions like their steaks cooked? Medium roar!',
  "What did the lion say to his cubs before they went out to play? 'Be prideful, my children!'",
  'Why did the lion eat the tightrope walker? He wanted a well-balanced meal!',
  'What do you get if you cross a lion and a snowman? Frostbite!',
  'Why did the lion lose at poker? Too many cheetahs!',
  'How do lions stay in shape? They have a pride fitness program!',
  'What do you call a lion who can repair anything? A duct-tape-lion!',
  'Why did the lioness get angry at the lion? He was always lion around!',
  "What's a lion's favorite type of music? Anything with a good roar-beat!",
  "Why don't lions mind the rain? Because they're already used to wet paws!",
  "What did the lion say to the lioness on Valentine's Day? 'You make my heart 'roar' with love!'",
  "What's a lion's favorite Shakespeare play? Romeo and Juliet, of course!",
  "Why don't lions play hide and seek? Because good luck hiding when you have a mane attraction!",
  "How do lions always know what's going on? They have a pride network!",
  'What do you call a lion who can solve math problems? A mathema-roar-tician!',
  'Why did the lion cross the road? To get to the mane event!',
  "What's a lion's favorite cookie? Snicker-roar-doodle!",
  'What do you call a lion who won the lottery? Mane-stream rich!',
  "How does a lion invite someone to dinner? With a roarin' good time!",
  'What do you call a lion who loves puns? A mane-iact!',
  'What do you call a lion who graduates top of his class? Valedictorian of the jungle!',
  'Why did the lion cross the road? To get to the other side (and roar, "I told you I could!")',
  'What do you call a lion that wins a spelling bee? A mane event!',
  'What do you call a lion who loves math? A pro-portional predator!',
  'What do you call a lion who opens a bakery? A roar-asting business!',
  'What do you call a lion who writes poetry? A verse-a-tile!',
  'What do you call a lion who loses his voice? A mime-o-lion!',
  'Why did the lion get an A on his report card? He was a purrfect student!',
  'What kind of music does a lion like? Jungle-beat!',
  'Why did the lion go to the dentist? To get his roar-alignment checked!',
  "What do you call a lion who's bad at directions? A pride-less wanderlust-er!",
  'Why did the lion get kicked out of the orchestra? He kept trying to conduct with his tail!',
  "What's the difference between a lion and a mattress? A mattress can hold up four legs!",
  "What do you call a lion who can't sleep? A restless mane-iac!",
  'What do you call a lion who can teleport? A poof-less predator!',
  'Why did the lion join the debate team? He wanted to roar his opinion!',
  'Why did the lion get expelled from school? He kept chewing on all the chairs!',
  'What do you call a lion who loves riddles? A Sphinx-ter (pronounced "finster")!',
  'What do you call a lion who loves to cook? A mane-course chef!',
  'What do you call a lion who loves to go camping? A pride-tent camper!',
  'What do you get when you cross a lion with a sheep? A woolly bully!',
  'Why did the lion get a speeding ticket? He was driving under the in-fluen-za of mane-ia!',
  'What do you call a lion who lost his mane? A bald-faced liar!',
  'What do you call a lion who loves to gossip? A jungle chatterbox!',
  'What do you call a lion who won a spelling bee? A mane-ific speller!',
  'Why did the lion join the chorus line? He wanted to be a part of the pride-formance!',
  "What do you call a lion who's always late? A mane-agerial mess!",
  'Why did the lion get detention? He kept lion-ing around!',
  "What do you call a lion who can't make up his mind? A wishy-washy mane-iac!",
  'What do you call a lion who just graduated from clown school? A funny-bone-anza!',
  "What do you call a lion who's really good at karate? A chop-suey-mane!",
  'Why did the lion get kicked out of the band? He kept saying, "I\'m the mane attraction!"',
  'What do you call a lion who loves cheese? A grate cheddar!',
];

export { lionJokes };
